services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      gunicorn main:app
      --workers 4
      --bind 0.0.0.0:8080
      --worker-class uvicorn.workers.UvicornWorker
    ports:
      - "8080:8080"
    depends_on:
      - weaviate
      - db
    env_file:
      - .env
    volumes:
      - ${PATH_BACKEND_DATA}:/app/keys
      - ${PATH_CERTS}:/app/certs
    networks:
      - internal

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 -m telegram_bot.bot_app
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - internal

  weaviate:
    image: semitechnologies/weaviate:latest
    expose:
      - "8080"
      - "50051"
    environment:
      CLUSTER_HOSTNAME: "node1"
      CLUSTER_GOSSIP_BIND_PORT: "7100"
      CLUSTER_JOIN: ""
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
    volumes:
      - ${PATH_WEAVIATE_DATA}:/var/lib/weaviate
    env_file:
      - .env
    networks:
      - internal

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PSWRD}
      POSTGRES_DB: ${SQL_DB}
    volumes:
      - ${PATH_PG_DATA}:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:
    driver: bridge
