services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - weaviate
      - db
    env_file:
      - .env
    networks:
      - internal

  weaviate:
    image: semitechnologies/weaviate:latest
    expose:
      - "8080"
      - "50051"
    environment:
      CLUSTER_HOSTNAME: "node1"
      CLUSTER_GOSSIP_BIND_PORT: "7100"
      CLUSTER_JOIN: ""
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
    volumes:
      - /home/shemkostya/weaviate_data:/var/lib/weaviate
    env_file:
      - .env
    networks:
      - internal

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PSWRD}
      POSTGRES_DB: ${SQL_DB}
    volumes:
      - /home/shemkostya/pg_data:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:
    driver: bridge