services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8181:8080"
      - "50051:50051"
    environment:
      CLUSTER_HOSTNAME: "node1"
      CLUSTER_GOSSIP_BIND_PORT: "7100"
      CLUSTER_JOIN: ""
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: reranker-openai
      OPENAI_APIKEY: ${OPENAI_API_KEY}
    volumes:
      - /home/shemkostya/weaviate_data:/var/lib/weaviate
    env_file:
      - /home/shemkostya/.env